language: node_js
node_js:
  - "0.12"
branches:
  only:
    - master
before_script:
  - npm install mocha -g
  - npm install grunt-cli -g
  - grunt config manifest dist-files
after_success:
  - grunt all
